# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "precise32"
  config.vm.hostname = "salt-master"
  
  config.vm.provision :salt do |salt|
    salt.install_master = true
    salt.master_config = "salt/minion"
    salt.verbose = true
  end
  
  
end
